CREATE TABLE LOCATION
(
    ID                             NUMBER NOT NULL,
    NAME                           NVARCHAR2(20) NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (ID),
    CONSTRAINT UK_LOCATION UNIQUE (NAME)
)
/
COMMENT ON TABLE LOCATION IS '場所'
/
COMMENT ON COLUMN LOCATION.ID IS 'ID'
/
COMMENT ON COLUMN LOCATION.NAME IS '名称'
/

