-- ユーザー作成
CREATE USER MRRS_DEV
IDENTIFIED BY MRRS
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
QUOTA UNLIMITED ON USERS
/

-- 権限付与
GRANT CONNECT TO MRRS_DEV
/
GRANT CREATE PROCEDURE TO MRRS_DEV
/
GRANT CREATE SEQUENCE TO MRRS_DEV
/
GRANT CREATE TABLE TO MRRS_DEV
/
GRANT CREATE TRIGGER TO MRRS_DEV
/
GRANT CREATE TYPE TO MRRS_DEV
/
GRANT CREATE VIEW TO MRRS_DEV
/
