CREATE TABLE RESERVATION
(
    ID                             NUMBER NOT NULL,
    MEETING_ROOM_ID                NUMBER NOT NULL,
    RESERVATION_START_DATE         DATE NOT NULL,
    RESERVATION_END_DATE           DATE NOT NULL,
    USER_NAME                      NVARCHAR2(50) NOT NULL,
    CONSTRAINT PK_RESERVATION PRIMARY KEY (ID),
    CONSTRAINT FK_RESERVATION_MEETING_ROOM FOREIGN KEY (MEETING_ROOM_ID) REFERENCES MEETING_ROOM (ID),
    CONSTRAINT UK_RESERVATION UNIQUE (MEETING_ROOM_ID, RESERVATION_START_DATE)
)
/
COMMENT ON TABLE RESERVATION IS '予約'
/
COMMENT ON COLUMN RESERVATION.ID IS 'ID'
/
COMMENT ON COLUMN RESERVATION.MEETING_ROOM_ID IS '会議室ID'
/
COMMENT ON COLUMN RESERVATION.RESERVATION_START_DATE IS '予約開始日時'
/
COMMENT ON COLUMN RESERVATION.RESERVATION_END_DATE IS '予約終了日時'
/
COMMENT ON COLUMN RESERVATION.USER_NAME IS '利用者'
/
