@startuml

[*] --> メニュー : アプリ起動

メニュー -up-> [*] : [終了]クリック
メニュー -left-> 場所管理 : [場所管理]クリック
メニュー -right-> 会議室一覧 : [会議室管理]クリック
メニュー --down-> 予約一覧 : [予約管理]クリック
メニュー : [場所管理]
メニュー : [会議室管理]
メニュー : [予約管理]
メニュー : [終了]

場所管理 -right-> メニュー : [保存] or [閉じる]クリック
場所管理 : 場所一覧
場所管理 : * 名称
場所管理 : * [削除]
場所管理 : [保存]
場所管理 : [閉じる]

会議室一覧 -up-> 会議室登録 : [新規登録]クリック
会議室一覧 -right-> 会議室変更 : [変更]クリック
会議室一覧 -down-> 会議室削除 : [削除]クリック
会議室一覧 -left-> メニュー : [閉じる]クリック
会議室登録 --> 会議室一覧 : [OK] or [キャンセル]クリック
会議室変更 --> 会議室一覧 : [OK] or [キャンセル]クリック
会議室削除 --> 会議室一覧 : [OK] or [キャンセル]クリック
会議室一覧 : 会議室一覧
会議室一覧 : * 場所
会議室一覧 : * 名称
会議室一覧 : * [変更]
会議室一覧 : * [削除]
会議室一覧 : [新規登録]
会議室一覧 : [閉じる]

予約一覧 -left-> 予約登録 : [新規登録]クリック
予約一覧 -down-> 予約変更 : [変更]クリック
予約一覧 -right-> 予約削除 : [削除]クリック
予約一覧 -up-> メニュー : [閉じる]クリック
予約登録 --> 予約一覧 : [OK] or [キャンセル]クリック
予約変更 --> 予約一覧 : [OK] or [キャンセル]クリック
予約削除 --> 予約一覧 : [OK] or [キャンセル]クリック
予約一覧 : 予約一覧
予約一覧 : * 場所
予約一覧 : * 会議室
予約一覧 : * 予約期間
予約一覧 : * 利用者
予約一覧 : * [変更]
予約一覧 : * [削除]
予約一覧 : [新規登録]
予約一覧 : [閉じる]

@enduml
